version: '3.8'

services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8011:8011"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/pesco_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=powergrid@2?.net
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - pluglr-springboot-network

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: pesco_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: powergrid@2?.net
    ports:
      - "5433:5432"
    networks:
      - pluglr-springboot-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: always
    networks:
      - pluglr-springboot-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pluglr-springboot-network

networks:
  pluglr-springboot-network:
    driver: bridge
